-- Create cars_relations table for blocking relationships (H2 compatible)
CREATE TABLE cars_relations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocking_car_id BIGINT NOT NULL,
    blocked_car_id BIGINT NOT NULL,
    FOREIGN KEY (blocking_car_id) REFERENCES cars(id) ON DELETE CASCADE,
    FOREIGN KEY (blocked_car_id) REFERENCES cars(id) ON DELETE CASCADE
);

CREATE INDEX idx_cars_relations_blocking ON cars_relations(blocking_car_id);
CREATE INDEX idx_cars_relations_blocked ON cars_relations(blocked_car_id);
