-- Create cars table for H2 database
CREATE TABLE cars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate_number VARCHAR(50) NOT NULL,
    country VARCHAR(50) NOT NULL,
    brand VARCHAR(100) DEFAULT 'UNKNOWN',
    model VARCHAR(255) NOT NULL,
    color VARCHAR(100) DEFAULT 'UNKNOWN',
    "year" INT NOT NULL,
    car_license_expire_date TIMESTAMP NULL,
    creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_cars_plate_number ON cars(plate_number);
